export const CONFIG_SCHEMA = {
    version: 1,
    export: {
        templates: {
            dataview: {
                name: "Obsidian Dataview",
                yamlMapping: {
                    date: 'date',
                    duration: 'duration',
                    type: 'workout_type',
                    tags: 'tags',
                },
                markdownTemplate: `# {templateName} - {date}

{exercises}

---
*Generated by Workout Tracker*`,
                description: "Optimized for Obsidian Dataview queries"
            },
            calendar: {
                name: "Calendar Format",
                yamlMapping: {
                    date: 'date',
                    duration: 'minutes',
                    type: 'category',
                    tags: 'tags',
                },
                markdownTemplate: `## {templateName}

{exercises}

*Workout completed in {duration} minutes*`,
                description: "Simple format for calendar views"
            },
            tracker: {
                name: "Workout Tracker",
                yamlMapping: {
                    date: 'workout_date',
                    duration: 'workout_duration',
                    type: 'training_type',
                    tags: 'workout_tags',
                },
                markdownTemplate: `# Workout Log - {date}

**Type:** {templateName}
**Duration:** {duration} min

{exercises}`,
                description: "Detailed workout tracking format"
            },
            custom: {
                name: "Custom Template",
                yamlMapping: {
                    date: 'date',
                    duration: 'duration',
                    type: 'type',
                    tags: 'tags',
                },
                markdownTemplate: `# {templateName}

{exercises}`,
                description: "User-customizable template"
            }
        },
        defaultTemplate: "dataview",
        filenamePattern: "{templateName} - {date}",
        autoOpenObsidian: true,
        includeTimestamp: true
    },
    
    ui: {
        theme: {
            colors: {
                background: '#000000',
                surface: '#121212',
                surfaceElevated: '#1E1E1E',
                primary: '#FFB100',
                text: '#FFFFFF',
                textMuted: '#A0A0A0',
                border: '#333333',
                borderActive: '#FFB100',
                error: '#FF4444',
                success: '#44FF44',
            },
            fonts: {
                primary: 'JetBrainsMono_400Regular',
                bold: 'JetBrainsMono_700Bold'
            },
            spacing: {
                xs: 4,
                sm: 8,
                md: 16,
                lg: 24,
                xl: 32,
                xxl: 48,
            },
            borders: {
                thin: 1,
                medium: 2,
                thick: 4,
                radius: 2,
            }
        },
        darkMode: true,
        accentColor: "#FFB100",
        showHints: true
    },
    
    workout: {
        defaults: {
            restTime: 60,
            defaultSets: 3,
            defaultReps: 10,
            exerciseType: "weighted"
        },
        volume: {
            includeBodyweight: false,
            userBodyweight: null,
            calculationMethod: "weight_x_reps"
        },
        tracking: {
            autoDuration: true,
            showVolume: true,
            showPRs: true,
            showRestTimer: true
        }
    },
    
    advanced: {
        dataManagement: {
            autoBackup: false,
            exportFormat: "json",
            retentionDays: 365,
            compressionEnabled: false
        },
        muscleGroups: {
            presets: ["GENERAL", "CHEST", "BACK", "LEGS", "SHOULDERS", "ARMS", "CORE"],
            allowCustom: true,
            sortAlphabetically: true
        },
        development: {
            debugMode: false,
            verboseLogging: false,
            enableTestMode: false
        }
    },
    
    meta: {
        version: 1,
        lastMigration: null,
        createdAt: null,
        updatedAt: null
    }
};

export const DEFAULT_CONFIG = {
    version: 1,
    export: {
        templates: {
            dataview: { ...CONFIG_SCHEMA.export.templates.dataview },
            calendar: { ...CONFIG_SCHEMA.export.templates.calendar },
            tracker: { ...CONFIG_SCHEMA.export.templates.tracker },
            custom: { ...CONFIG_SCHEMA.export.templates.custom }
        },
        defaultTemplate: "dataview",
        filenamePattern: "{templateName} - {date}",
        autoOpenObsidian: true,
        includeTimestamp: true
    },
    
    ui: {
        theme: {
            colors: { ...CONFIG_SCHEMA.ui.theme.colors },
            fonts: { ...CONFIG_SCHEMA.ui.theme.fonts },
            spacing: { ...CONFIG_SCHEMA.ui.theme.spacing },
            borders: { ...CONFIG_SCHEMA.ui.theme.borders }
        },
        darkMode: true,
        accentColor: "#FFB100",
        showHints: true
    },
    
    workout: {
        defaults: {
            restTime: 60,
            defaultSets: 3,
            defaultReps: 10,
            exerciseType: "weighted"
        },
        volume: {
            includeBodyweight: false,
            userBodyweight: null,
            calculationMethod: "weight_x_reps"
        },
        tracking: {
            autoDuration: true,
            showVolume: true,
            showPRs: true,
            showRestTimer: true
        }
    },
    
    advanced: {
        dataManagement: {
            autoBackup: false,
            exportFormat: "json",
            retentionDays: 365,
            compressionEnabled: false
        },
        muscleGroups: {
            presets: ["GENERAL", "CHEST", "BACK", "LEGS", "SHOULDERS", "ARMS", "CORE"],
            allowCustom: true,
            sortAlphabetically: true
        },
        development: {
            debugMode: false,
            verboseLogging: false,
            enableTestMode: false
        }
    },
    
    meta: {
        version: 1,
        lastMigration: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    }
};

export const ConfigSchema = {
    validate(config) {
        const errors = [];
        
        if (!config || typeof config !== 'object') {
            errors.push("Config must be an object");
            return { valid: false, errors };
        }
        
        if (config.export) {
            if (config.export.defaultTemplate && !CONFIG_SCHEMA.export.templates[config.export.defaultTemplate]) {
                errors.push(`Invalid defaultTemplate: ${config.export.defaultTemplate}`);
            }
            
            if (config.export.filenamePattern && typeof config.export.filenamePattern !== 'string') {
                errors.push("filenamePattern must be a string");
            }
        }
        
        if (config.workout) {
            if (config.workout.defaults) {
                const { defaults } = config.workout;
                if (defaults.restTime !== undefined && (typeof defaults.restTime !== 'number' || defaults.restTime < 0)) {
                    errors.push("restTime must be a positive number");
                }
                if (defaults.defaultSets !== undefined && (typeof defaults.defaultSets !== 'number' || defaults.defaultSets < 1)) {
                    errors.push("defaultSets must be a positive number");
                }
                if (defaults.defaultReps !== undefined && (typeof defaults.defaultReps !== 'number' || defaults.defaultReps < 1)) {
                    errors.push("defaultReps must be a positive number");
                }
            }
            
            if (config.workout.volume) {
                const { volume } = config.workout;
                if (volume.userBodyweight !== undefined && (typeof volume.userBodyweight !== 'number' || volume.userBodyweight < 0)) {
                    errors.push("userBodyweight must be a positive number");
                }
            }
        }
        
        if (config.ui) {
            if (config.ui.accentColor && typeof config.ui.accentColor !== 'string') {
                errors.push("accentColor must be a string");
            }
        }
        
        // Allow null userBodyweight as it's a valid state (not set)
        if (config.workout?.volume?.userBodyweight === null) {
            const userBodyweightErrorIndex = errors.findIndex(e => e.includes('userBodyweight must be a positive number'));
            if (userBodyweightErrorIndex > -1) {
                errors.splice(userBodyweightErrorIndex, 1);
            }
        }
        
        return { valid: errors.length === 0, errors };
    },
    
    getDefaults(section = null) {
        if (!section) return DEFAULT_CONFIG;
        
        const keys = section.split('.');
        let result = DEFAULT_CONFIG;
        
        for (const key of keys) {
            if (result && result[key] !== undefined) {
                result = result[key];
            } else {
                return null;
            }
        }
        
        return result;
    },
    
    migrate(config, fromVersion, toVersion) {
        let migrated = { ...config };
        
        if (fromVersion === 0 && toVersion >= 1) {
            migrated = this.migrateFromLegacy(migrated);
        }
        
        return migrated;
    },
    
    migrateFromLegacy(legacySettings) {
        const config = { ...DEFAULT_CONFIG };
        
        if (legacySettings.yamlMapping) {
            // Remove volume mapping from legacy settings to prevent migration of obsolete field
            const { volume, ...cleanYamlMapping } = legacySettings.yamlMapping;
            config.export.templates.dataview.yamlMapping = { ...cleanYamlMapping };
            config.export.templates.custom.yamlMapping = { ...cleanYamlMapping };
        }
        
        // Clean volume mappings from any existing template configurations
        if (legacySettings.export?.templates) {
            Object.keys(legacySettings.export.templates).forEach(templateKey => {
                if (legacySettings.export.templates[templateKey].yamlMapping?.volume) {
                    delete legacySettings.export.templates[templateKey].yamlMapping.volume;
                }
            });
        }
        
        if (legacySettings.tags) {
        }
        
        if (legacySettings.userBodyweight !== undefined) {
            config.workout.volume.userBodyweight = legacySettings.userBodyweight;
        }
        
        config.meta.lastMigration = '0->1';
        config.meta.updatedAt = new Date().toISOString();
        
        return config;
    }
};